from app import create_app
from controllers.database import db
from controllers.models import Application
from controllers.tasks import send_interview_reminders, generate_monthly_placement_reports
from datetime import datetime, timedelta

app, _ = create_app()

with app.app_context():
    print("====================================")
    print("         CareerLink Jobs Demo       ")
    print("====================================\n")
    
    # 1. Prepare data (Force an interview date to tomorrow)
    app_record = Application.query.first()
    if app_record:
        tomorrow = datetime.utcnow() + timedelta(days=1)
        app_record.interview_date = tomorrow
        db.session.commit()
    else:
        print("[!] No applications found in the database. Please create an application through the UI first.")
        exit(1)

    # 2. Trigger the automated daily job
    print("--- 1. TRIGGERING DAILY INTERVIEW REMINDERS (Mocked as if midnight) ---")
    send_interview_reminders()
    print("\n")
    
    # 3. Trigger the automated monthly report
    print("--- 2. TRIGGERING MONTHLY PLACEMENT REPORT (Mocked as if 1st of month) ---")
    generate_monthly_placement_reports()
    
    # Generate a visual HTML file just for the demo
    import os
    os.makedirs('exports', exist_ok=True)
    with open('exports/demo_monthly_report.html', 'w') as f:
        f.write("<h2>Monthly Placement Report</h2><p>Auto-generated by Celery Job mock.</p><p>Total Placements: 2</p>")
    
    print("\n")
    
    print("====================================")
    print("           DEMO COMPLETE            ")
    print(" Check backend/exports for report!  ")
    print("====================================")
